### ISSUE TITLE
Documentation for IRC actually points to a Matrix channel

### ISSUE THREAD

**Issue by NattyNarwhal** [betrusted-io/betrusted-wiki#19]
Not sure where's the best place for this. The "Quick Start Guide" says the channel is on IRC, but only points to a Matrix channel (`#betrusted:matrix.org`) - is this a mistake, and the channel is Matrix only? Or is there an IRC channel somewhere I'm not aware of? `#betrusted` doesn't exist on Libera or OFTC.

**Comment by bunnie** [comment]
hmm. I'm not an expert IRC user but at least my client has the option to connect to the matrix.org IRC server and that is where the channel is located. but I can totally believe that we've missed some important facet like cross server federation because I'm not very good at configuring IRC.

**Comment by NattyNarwhal** [comment]
I didn't know Matrix was running their own IRC server - I thought they just relied on bridging with existing networks like Libera. If that's the case, it would help to specify something like, "Join our Matrix channel `#betrusted:matrix.org` (bridged to IRC channel `irc.matrix.org` `#betrusted`)" (or whatever the channel actually is) to be clear.

**Comment by bunnie** [comment]
Hm. Let me ask someone in the IRC channel to try and improve those instructions, I don't know IRC well enough to figure this out.

**Comment by bunnie** [comment]
Alright, the root cause is my ignorance of how Matrix and IRC are related. Matrix can talk to IRC, but IRC can't talk to Matrix, therefore it is inappropriate to say our thing is an IRC channel. It's actually a Matrix channel. I'll update the text in the print file but I'm not going to scrap the existing print run of manuals (which was a lot of them) to fix this problem.
